### ISSUE TITLE
Unable to load Google Doc or MS Office viewer on LAN IP address

### ISSUE THREAD

**Issue by tobychui** [yeungalan/office_viewer#2]
When trying to open a file in ArozOS connecting using LAN IP address, the following error show up on MS Office Viewer
![圖片](https://user-images.githubusercontent.com/24617523/146782407-626d4ba4-3ca4-4856-b2cf-437c96c01da4.png)

After switching to Google Viewer, the interface get stuck here and not doing any redirection
![圖片](https://user-images.githubusercontent.com/24617523/146782854-0728bcda-330f-4094-8c51-4e4a65377f42.png)

and the Network tab return no content for the Google Viewer
![圖片](https://user-images.githubusercontent.com/24617523/146783016-5a580c31-a0f9-4184-ad87-0c0bbaf7c58b.png)

I guess it would be better to find a solution to this issue, either pop up a new interface to ask if the user want to access ArozOS with the DNS returned domain or simply pop up an error message when the target return no content / error. 

What do you think?

**Comment by yeungalan** [comment]
Fixed in this two commit
dbcae0ad2a62c70482ecf484558ee31c95a88fd7
6846df1de9d73f7bb89e347ce053723d492d990b
